# Generated by Django 3.2.18 on 2023-03-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='attached_documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associated_doc', models.FileField(blank=True, upload_to='Tasks_Documents', verbose_name='Associated Document')),
                ('proof_of_completion', models.FileField(blank=True, upload_to='Tasks_Complete_Documents', verbose_name='Complete Proof Document')),
            ],
            options={
                'verbose_name_plural': 'Associated Doc',
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='associated_documents',
            field=models.ManyToManyField(blank=True, null=True, to='Home.attached_documents'),
        ),
    ]
