# Generated by Django 3.2.18 on 2023-03-12 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('picture', models.ImageField(blank=True, upload_to='Profil_Images')),
                ('gender', models.CharField(blank=True, max_length=25, null=True)),
                ('profession', models.CharField(blank=True, max_length=25, null=True)),
                ('otp', models.CharField(blank=True, max_length=25, null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
